import { CardData } from "../components/parallax/ParallaxCard";

// Edit this list to add, remove, or update events — the rest of the page is data-driven.
export const eventCards: CardData[] = [
  // ── Competitions ────────────────────────────────────────
  {
    id: "code-combat",
    title: "Code Combat",
    subtitle: "High-Stakes Competitive Programming",
    type: "Competition",
    category: "competition",
    Duration: 1,
    Seats: 200,
    Level: 4,
    image: "/tiles/tile-01.jpg",
    accentColor: "#33d6ff",
    glowColor: "rgba(51,214,255,.5)",
    foilGradient: "linear-gradient(135deg,#0b1c2f,#123f5d,#081019)",
    badgeIcon: "⚔️",
    description:
      "A high-intensity competitive programming arena where participants solve algorithmic challenges under pressure. Solo or team — survive the leaderboard.",
    tags: ["Competition", "DSA", "Leaderboard"],
    price: "Free Entry",
    layout: {
      top: "130vh",
      left: "43%",
      width: "clamp(270px, 72vw, 500px)",
    },
  },
  {
    id: "hackathon",
    title: "Hackathon",
    subtitle: "24-Hour Build Sprint",
    type: "Build Sprint",
    category: "competition",
    Duration: 1,
    Seats: 150,
    Level: 3,
    image: "/tiles/tile-02.jpg",
    accentColor: "#f59e0b",
    glowColor: "rgba(245,158,11,.5)",
    foilGradient: "linear-gradient(135deg,#1a1005,#3d2a10,#0d0803)",
    badgeIcon: "💻",
    description:
      "A marathon build sprint where cross-disciplinary teams prototype real-world solutions. Judged on impact, creativity, and technical execution.",
    tags: ["Hackathon", "Teams", "Build"],
    price: "Free Entry",
    layout: {
      top: "175vh",
      right: "10%",
      width: "clamp(270px, 72vw, 450px)",
    },
  },
  {
    id: "robo-war",
    title: "Robo War",
    subtitle: "Combat Robotics Arena",
    type: "Robotics",
    category: "competition",
    Duration: 1,
    Seats: 60,
    Level: 4,
    image: "/tiles/tile-04.jpg",
    accentColor: "#ef4444",
    glowColor: "rgba(239,68,68,.5)",
    foilGradient: "linear-gradient(135deg,#1a0505,#3d1010,#0d0303)",
    badgeIcon: "🤖",
    description:
      "Combat robotics arena — custom-built bots face off in elimination rounds. Categories include autonomous, remote-controlled, and mini-sumo.",
    tags: ["Robotics", "Combat", "Elimination"],
    price: "₹999",
    layout: {
      top: "220vh",
      left: "35%",
      width: "clamp(270px, 72vw, 480px)",
    },
  },

  // ── Showcase & Culture ────────────────────────────────────
  {
    id: "tech-talks",
    title: "Tech Talk Series",
    subtitle: "Keynotes From Industry Pioneers",
    type: "Talks",
    category: "showcase",
    Duration: 1,
    Seats: 500,
    Level: 1,
    image: "/tiles/tile-03.jpg",
    accentColor: "#a855f7",
    glowColor: "rgba(168,85,247,.5)",
    foilGradient: "linear-gradient(135deg,#1a0b2e,#3b1d6e,#0d0520)",
    badgeIcon: "🎤",
    description:
      "Keynote sessions and panel discussions led by industry pioneers and researchers. Topics span AI, space systems, sustainability, and emerging tech.",
    tags: ["Talks", "Keynote", "Panel"],
    price: "Free Entry",
    layout: {
      top: "265vh",
      right: "45%",
      width: "clamp(270px, 72vw, 520px)",
    },
  },
  {
    id: "innovation-expo",
    title: "Innovation Expo",
    subtitle: "Project Exhibition & Demos",
    type: "Exhibition",
    category: "showcase",
    Duration: 1,
    Seats: 300,
    Level: 1,
    image: "/tiles/tile-07.jpg",
    accentColor: "#10b981",
    glowColor: "rgba(16,185,129,.5)",
    foilGradient: "linear-gradient(135deg,#051a10,#0f3d25,#030d08)",
    badgeIcon: "🌟",
    description:
      "Project exhibition where student teams showcase research prototypes, hardware builds, and proof-of-concept demos to a panel of judges and industry visitors.",
    tags: ["Exhibition", "Research", "Demo"],
    price: "Free Entry",
    layout: {
      top: "310vh",
      left: "10%",
      width: "clamp(270px, 72vw, 460px)",
    },
  },
  {
    id: "cultural-night",
    title: "Cultural Night",
    subtitle: "Music, Dance & Performances",
    type: "Cultural",
    category: "showcase",
    Duration: 1,
    Seats: 800,
    Level: 1,
    image: "/tiles/tile-05.jpeg",
    accentColor: "#ec4899",
    glowColor: "rgba(236,72,153,.5)",
    foilGradient: "linear-gradient(135deg,#1a0515,#3d1030,#0d0310)",
    badgeIcon: "🎭",
    description:
      "An evening of music, dance, and performances that celebrate the creative spirit of the community. The perfect close to a day of high-energy competition.",
    tags: ["Cultural", "Music", "Dance"],
    price: "Free Entry",
    layout: {
      top: "352.5vh",
      right: "50%",
      width: "clamp(270px, 72vw, 470px)",
    },
  },
];
