import { CardData } from "../components/parallax/ParallaxCard";

export const workshopCards: CardData[] = [
  // ── Pre-Conscientia ─────────────────────────────────────
  {
    id: "rocket",
    title: "Advanced Rocketry Workshop",
    subtitle: "Engineering the Future Through Time",
    type: "Rocketry",
    category: "pre",
    Duration: 3,
    Seats: 120,
    Level: 2,
    image: "/tiles/tile-01.jpg",
    accentColor: "#33d6ff",
    glowColor: "rgba(51,214,255,.5)",
    foilGradient: "linear-gradient(135deg,#0b1c2f,#123f5d,#081019)",
    badgeIcon: "🚀",
    description:
      "Explore propulsion, aerodynamics, guidance systems and launch simulations.",
    tags: ["Rocketry", "Hands-on", "IIST", "Workshop"],
    price: "\u20B92,499",
    layout: {
      top: "130vh",
      left: "43%",
      width: "500px",
    },
  },
  {
    id: "ai-ml",
    title: "AI & Machine Learning",
    subtitle: "Neural Networks & Deep Learning",
    type: "AI/ML",
    category: "pre",
    Duration: 5,
    Seats: 80,
    Level: 3,
    image: "/tiles/tile-02.jpg",
    accentColor: "#a855f7",
    glowColor: "rgba(168,85,247,.5)",
    foilGradient: "linear-gradient(135deg,#1a0b2e,#3b1d6e,#0d0520)",
    badgeIcon: "🤖",
    description:
      "Build intelligent systems with neural networks, transformers and generative AI models.",
    tags: ["AI", "Python", "Deep Learning", "GPU"],
    price: "\u20B93,999",
    layout: {
      top: "175vh",
      right: "10%",
      width: "450px",
    },
  },
  {
    id: "cybersec",
    title: "Cybersecurity Bootcamp",
    subtitle: "Defend the Digital Frontier",
    type: "Security",
    category: "pre",
    Duration: 4,
    Seats: 60,
    Level: 4,
    image: "/tiles/tile-03.jpg",
    accentColor: "#22c55e",
    glowColor: "rgba(34,197,94,.5)",
    foilGradient: "linear-gradient(135deg,#0a1f12,#1a4a2e,#061208)",
    badgeIcon: "🛡️",
    description:
      "Master penetration testing, cryptography, network defense and incident response.",
    tags: ["CyberSec", "CTF", "Ethical Hacking", "Linux"],
    price: "\u20B93,499",
    layout: {
      top: "220vh",
      left: "35%",
      width: "480px",
    },
  },
  {
    id: "robotics",
    title: "Robotics & Automation",
    subtitle: "Machines That Think and Act",
    type: "Robotics",
    category: "pre",
    Duration: 6,
    Seats: 50,
    Level: 3,
    image: "/tiles/tile-04.jpg",
    accentColor: "#f97316",
    glowColor: "rgba(249,115,22,.5)",
    foilGradient: "linear-gradient(135deg,#1a0f05,#3d2410,#0d0703)",
    badgeIcon: "🤖",
    description:
      "Design, build and program autonomous robots with sensors, actuators and AI control.",
    tags: ["Robotics", "Arduino", "ROS", "Mechatronics"],
    price: "\u20B94,499",
    layout: {
      top: "265vh",
      right: "45%",
      width: "520px",
    },
  },
  {
    id: "quantum",
    title: "Quantum Computing Lab",
    subtitle: "Beyond Classical Computation",
    type: "Quantum",
    category: "pre",
    Duration: 3,
    Seats: 40,
    Level: 5,
    image: "/tiles/tile-05.jpeg",
    accentColor: "#ec4899",
    glowColor: "rgba(236,72,153,.5)",
    foilGradient: "linear-gradient(135deg,#1a0515,#3d1030,#0d0310)",
    badgeIcon: "⚛️",
    description:
      "Explore qubits, quantum gates, entanglement and run algorithms on real quantum hardware.",
    tags: ["Quantum", "Qiskit", "Physics", "Research"],
    price: "\u20B95,999",
    layout: {
      top: "310vh",
      left: "10%",
      width: "460px",
    },
  },
  {
    id: "data-science",
    title: "Data Science & Analytics",
    subtitle: "Insights From Raw Information",
    type: "Data Science",
    category: "pre",
    Duration: 4,
    Seats: 95,
    Level: 2,
    image: "/tiles/tile-07.jpg",
    accentColor: "#6366f1",
    glowColor: "rgba(99,102,241,.5)",
    foilGradient: "linear-gradient(135deg,#0f0a2e,#251d6e,#080520)",
    badgeIcon: "📊",
    description:
      "Master statistical analysis, data visualization, and predictive modeling with real-world datasets.",
    tags: ["Data Science", "Python", "SQL", "Analytics"],
    price: "\u20B93,199",
    layout: {
      top: "352.5vh",
      right: "50%",
      width: "470px",
    },
  },
  {
    id: "cloud",
    title: "Cloud & DevOps",
    subtitle: "Infrastructure at Scale",
    type: "Cloud",
    category: "pre",
    Duration: 4,
    Seats: 75,
    Level: 3,
    image: "/tiles/tile-08.jpg",
    accentColor: "#0ea5e9",
    glowColor: "rgba(14,165,233,.5)",
    foilGradient: "linear-gradient(135deg,#071a2f,#10405a,#040e18)",
    badgeIcon: "☁️",
    description:
      "Deploy, scale and manage applications on AWS, GCP and Azure with CI/CD pipelines.",
    tags: ["Cloud", "AWS", "Docker", "Kubernetes"],
    price: "\u20B93,699",
    layout: {
      top: "395vh",
      left: "30%",
      width: "480px",
    },
  },

  // ── Live-Conscientia ────────────────────────────────────
  {
    id: "aerospace",
    title: "Aerospace Engineering",
    subtitle: "Designing Aircraft of Tomorrow",
    type: "Aerospace",
    category: "live",
    Duration: 4,
    Seats: 90,
    Level: 2,
    image: "/tiles/tile-06.jpg",
    accentColor: "#06b6d4",
    glowColor: "rgba(6,182,212,.5)",
    foilGradient: "linear-gradient(135deg,#071a1f,#103d4a,#040e12)",
    badgeIcon: "✈️",
    description:
      "Study aerodynamics, flight mechanics, structural design and wind tunnel testing.",
    tags: ["Aerospace", "CFD", "CAD", "Simulation"],
    price: "\u20B93,799",
    layout: {
      top: "470vh",
      right: "20%",
      width: "490px",
    },
  },
  {
    id: "blockchain",
    title: "Blockchain Development",
    subtitle: "Decentralized Systems & Web3",
    type: "Web3",
    category: "live",
    Duration: 4,
    Seats: 70,
    Level: 3,
    image: "/tiles/tile-07.jpg",
    accentColor: "#eab308",
    glowColor: "rgba(234,179,8,.5)",
    foilGradient: "linear-gradient(135deg,#1a1505,#3d3410,#0d0a03)",
    badgeIcon: "⛓️",
    description:
      "Build smart contracts, DeFi protocols and decentralized applications on Ethereum and Solana.",
    tags: ["Blockchain", "Solidity", "Web3", "Crypto"],
    price: "\u20B93,299",
    layout: {
      top: "520vh",
      left: "55%",
      width: "470px",
    },
  },
  {
    id: "iot",
    title: "Internet of Things Lab",
    subtitle: "Connected Devices & Edge Computing",
    type: "IoT",
    category: "live",
    Duration: 3,
    Seats: 55,
    Level: 2,
    image: "/tiles/tile-08.jpg",
    accentColor: "#14b8a6",
    glowColor: "rgba(20,184,166,.5)",
    foilGradient: "linear-gradient(135deg,#071a17,#103d35,#040e0c)",
    badgeIcon: "📡",
    description:
      "Design sensor networks, embedded systems and real-time data pipelines for smart environments.",
    tags: ["IoT", "Arduino", "Sensors", "Edge"],
    price: "\u20B92,999",
    layout: {
      top: "570vh",
      right: "10%",
      width: "510px",
    },
  },
  {
    id: "biotech",
    title: "Biotech & Genomics",
    subtitle: "Code Meets Biology",
    type: "Biotech",
    category: "live",
    Duration: 5,
    Seats: 45,
    Level: 4,
    image: "/tiles/tile-05.jpeg",
    accentColor: "#f43f5e",
    glowColor: "rgba(244,63,94,.5)",
    foilGradient: "linear-gradient(135deg,#1a0510,#3d1028,#0d030a)",
    badgeIcon: "🧬",
    description:
      "Analyze genomic data, model protein structures and build bioinformatics pipelines.",
    tags: ["Biotech", "Genomics", "Python", "Research"],
    price: "\u20B94,799",
    layout: {
      top: "615vh",
      left: "45%",
      width: "480px",
    },
  },
];
