-- Replaces the entire event catalog with the real Conscientia 2026 event
-- lineup — every previous event (code-combat, hackathon, robo-war,
-- tech-talks, innovation-expo, cultural-night) is removed. Workshops are
-- untouched. This is the only place events are defined; the frontend has
-- no static fallback (see src/lib/catalogStore.js).
delete from public.catalog_items where kind = 'event';
delete from public.tickets where type = 'event';

insert into public.tickets (id, type, cost, ticket_id) values
  ('bgmi', 'event', '₹399', 3129),
  ('ff', 'event', '₹399', 3129),
  ('clashroyale', 'event', '₹99', 3132),
  ('gg', 'event', '₹99', 3132),
  ('cicada', 'event', '₹199', 3131),
  ('battleofbots', 'event', '₹1799', 3133),
  ('dronetrix', 'event', '₹799', 3134),
  ('rcrallycross', 'event', '₹699', 3126),
  ('hackorbitalteam', 'event', '₹1799', 3133),
  ('hackorbitalindividual', 'event', '₹349', 3135),
  ('cansat', 'event', '₹999', 3138),
  ('robosoccer', 'event', '₹699', 3126),
  ('rcplane', 'event', '₹699', 3126),
  ('amphibot', 'event', '₹699', 3126),
  ('quantasiateam', 'event', '₹1499', 3139),
  ('quantasiaindividual', 'event', '₹399', 3129),
  ('linefollower', 'event', '₹499', 3128),
  ('mazesolver', 'event', '₹499', 3128),
  ('codeclash', 'event', '₹299', 3130),
  ('arduinohackathon', 'event', '₹399', 3129),
  ('circuiter', 'event', '₹399', 3129),
  ('thrilltopia', 'event', '₹99', 3132),
  ('counterpoint', 'event', '₹299', 3130),
  ('conscientiafootballcup', 'event', '₹599', 3127),
  ('mocksharktank', 'event', '₹249', 3136),
  ('cricketauction', 'event', '₹199', 3131),
  ('xenohabitatdesign', 'event', '₹199', 3131),
  ('intbee', 'event', '₹199', 3131),
  ('generalquiz', 'event', '₹199', 3131),
  ('spacequiz', 'event', '₹99', 3132),
  ('hammertime', 'event', '₹99', 3132),
  ('ahogwartsmystery', 'event', '₹299', 3130),
  ('escapetheupsidedown', 'event', '₹125', 3137);

insert into public.catalog_items (
  id, kind, sort_order,
  title, subtitle, type,
  section, section_color,
  duration, seats,
  eligibility, venue, timing,
  image, badge_icon,
  accent_color, glow_color, foil_gradient,
  description,
  about_extra, highlights, requirements,
  format, certificate, tags,
  brochure_url, layout, contacts
) values
  (
    'bgmi', 'event', 0,
    'BGMI', 'Conscientia 2026', 'BGMI',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/bgmi/800/600', '🎮',
    '#33d6ff', 'rgba(51,214,255,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'BGMI — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["BGMI"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'ff', 'event', 1,
    'Free Fire', 'Conscientia 2026', 'Free Fire',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/ff/800/600', '🎮',
    '#a855f7', 'rgba(168,85,247,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Free Fire — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Free Fire"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'clashroyale', 'event', 2,
    'Clash Royale', 'Conscientia 2026', 'Clash Royale',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/clashroyale/800/600', '🎮',
    '#22c55e', 'rgba(34,197,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Clash Royale — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Clash Royale"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'gg', 'event', 3,
    'GG', 'Conscientia 2026', 'GG',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/gg/800/600', '🎮',
    '#f97316', 'rgba(249,115,22,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'GG — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["GG"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'cicada', 'event', 4,
    'Cicada', 'Conscientia 2026', 'Cicada',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/cicada/800/600', '🧠',
    '#f97316', 'rgba(249,115,22,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Cicada — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Cicada"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'battleofbots', 'event', 5,
    'Battle of Bots', 'Conscientia 2026', 'Battle of Bots',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/battleofbots/800/600', '🤖',
    '#ec4899', 'rgba(236,72,153,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Battle of Bots — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Battle of Bots"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'dronetrix', 'event', 6,
    'Dronetrix', 'Conscientia 2026', 'Dronetrix',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/dronetrix/800/600', '🚁',
    '#6366f1', 'rgba(99,102,241,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Dronetrix — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Dronetrix"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'rcrallycross', 'event', 7,
    'RC Rallycross', 'Conscientia 2026', 'RC Rallycross',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/rcrallycross/800/600', '🏎️',
    '#0ea5e9', 'rgba(14,165,233,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'RC Rallycross — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["RC Rallycross"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'hackorbitalteam', 'event', 8,
    'HackOrbital (Team)', 'Conscientia 2026', 'HackOrbital (Team)',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/hackorbitalteam/800/600', '💻',
    '#eab308', 'rgba(234,179,8,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'HackOrbital (Team) — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["HackOrbital (Team)"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'hackorbitalindividual', 'event', 9,
    'HackOrbital (Individual)', 'Conscientia 2026', 'HackOrbital (Individual)',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/hackorbitalindividual/800/600', '💻',
    '#14b8a6', 'rgba(20,184,166,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'HackOrbital (Individual) — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["HackOrbital (Individual)"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'cansat', 'event', 10,
    'CanSat', 'Conscientia 2026', 'CanSat',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/cansat/800/600', '🛰️',
    '#f43f5e', 'rgba(244,63,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'CanSat — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["CanSat"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'robosoccer', 'event', 11,
    'RoboSoccer', 'Conscientia 2026', 'RoboSoccer',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/robosoccer/800/600', '⚽',
    '#33d6ff', 'rgba(51,214,255,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'RoboSoccer — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["RoboSoccer"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'rcplane', 'event', 12,
    'RC Plane', 'Conscientia 2026', 'RC Plane',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/rcplane/800/600', '✈️',
    '#a855f7', 'rgba(168,85,247,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'RC Plane — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["RC Plane"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'amphibot', 'event', 13,
    'AmphiBot', 'Conscientia 2026', 'AmphiBot',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/amphibot/800/600', '🤖',
    '#22c55e', 'rgba(34,197,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'AmphiBot — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["AmphiBot"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'quantasiateam', 'event', 14,
    'Quantasia (Team)', 'Conscientia 2026', 'Quantasia (Team)',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/quantasiateam/800/600', '⚛️',
    '#f97316', 'rgba(249,115,22,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Quantasia (Team) — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Quantasia (Team)"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'quantasiaindividual', 'event', 15,
    'Quantasia (Individual)', 'Conscientia 2026', 'Quantasia (Individual)',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/quantasiaindividual/800/600', '⚛️',
    '#ec4899', 'rgba(236,72,153,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Quantasia (Individual) — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Quantasia (Individual)"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'linefollower', 'event', 16,
    'Line Follower', 'Conscientia 2026', 'Line Follower',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/linefollower/800/600', '🤖',
    '#6366f1', 'rgba(99,102,241,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Line Follower — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Line Follower"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'mazesolver', 'event', 17,
    'Maze Solver', 'Conscientia 2026', 'Maze Solver',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/mazesolver/800/600', '🤖',
    '#0ea5e9', 'rgba(14,165,233,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Maze Solver — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Maze Solver"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'codeclash', 'event', 18,
    'Code Clash', 'Conscientia 2026', 'Code Clash',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/codeclash/800/600', '💻',
    '#eab308', 'rgba(234,179,8,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Code Clash — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Code Clash"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'arduinohackathon', 'event', 19,
    'Arduino Hackathon', 'Conscientia 2026', 'Arduino Hackathon',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/arduinohackathon/800/600', '💻',
    '#14b8a6', 'rgba(20,184,166,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Arduino Hackathon — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Arduino Hackathon"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'circuiter', 'event', 20,
    'Circuiter', 'Conscientia 2026', 'Circuiter',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/circuiter/800/600', '🔌',
    '#f43f5e', 'rgba(244,63,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Circuiter — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Circuiter"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'thrilltopia', 'event', 21,
    'Thrilltopia', 'Conscientia 2026', 'Thrilltopia',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/thrilltopia/800/600', '🎉',
    '#ec4899', 'rgba(236,72,153,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Thrilltopia — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Thrilltopia"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'counterpoint', 'event', 22,
    'Counterpoint', 'Conscientia 2026', 'Counterpoint',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/counterpoint/800/600', '🎤',
    '#6366f1', 'rgba(99,102,241,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Counterpoint — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Counterpoint"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'conscientiafootballcup', 'event', 23,
    'Conscientia Football Cup', 'Conscientia 2026', 'Conscientia Football Cup',
    'Competitions', '#33d6ff',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/conscientiafootballcup/800/600', '⚽',
    '#33d6ff', 'rgba(51,214,255,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Conscientia Football Cup — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Conscientia Football Cup"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'mocksharktank', 'event', 24,
    'Mock Shark Tank', 'Conscientia 2026', 'Mock Shark Tank',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/mocksharktank/800/600', '🦈',
    '#0ea5e9', 'rgba(14,165,233,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Mock Shark Tank — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Mock Shark Tank"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'cricketauction', 'event', 25,
    'Cricket Auction', 'Conscientia 2026', 'Cricket Auction',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/cricketauction/800/600', '🏏',
    '#eab308', 'rgba(234,179,8,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Cricket Auction — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Cricket Auction"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'xenohabitatdesign', 'event', 26,
    'Xenohabitat Design', 'Conscientia 2026', 'Xenohabitat Design',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/xenohabitatdesign/800/600', '🪐',
    '#14b8a6', 'rgba(20,184,166,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Xenohabitat Design — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Xenohabitat Design"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'intbee', 'event', 27,
    'IntBee', 'Conscientia 2026', 'IntBee',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/intbee/800/600', '🐝',
    '#f43f5e', 'rgba(244,63,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'IntBee — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["IntBee"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'generalquiz', 'event', 28,
    'General Quiz', 'Conscientia 2026', 'General Quiz',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/generalquiz/800/600', '🧠',
    '#33d6ff', 'rgba(51,214,255,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'General Quiz — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["General Quiz"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'spacequiz', 'event', 29,
    'Space Quiz', 'Conscientia 2026', 'Space Quiz',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/spacequiz/800/600', '🧠',
    '#a855f7', 'rgba(168,85,247,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Space Quiz — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Space Quiz"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'hammertime', 'event', 30,
    'Hammer Time', 'Conscientia 2026', 'Hammer Time',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/hammertime/800/600', '🔨',
    '#22c55e', 'rgba(34,197,94,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Hammer Time — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Hammer Time"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'ahogwartsmystery', 'event', 31,
    'A Hogwarts Mystery', 'Conscientia 2026', 'A Hogwarts Mystery',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/ahogwartsmystery/800/600', '🪄',
    '#f97316', 'rgba(249,115,22,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'A Hogwarts Mystery — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["A Hogwarts Mystery"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  ),
  (
    'escapetheupsidedown', 'event', 32,
    'Escape the Upside Down', 'Conscientia 2026', 'Escape the Upside Down',
    'Showcase & Culture', '#a855f7',
    1, 0,
    '', '', '',
    'https://picsum.photos/seed/escapetheupsidedown/800/600', '🎭',
    '#ec4899', 'rgba(236,72,153,.5)', 'linear-gradient(135deg,#0b1c2f,#123f5d,#081019)',
    'Escape the Upside Down — part of Conscientia 2026.',
    '[]'::jsonb, '[]'::jsonb, '[]'::jsonb,
    'In-Person', 'Participation certificate for all entrants', '["Escape the Upside Down"]'::jsonb,
    '', '{}'::jsonb, '[]'::jsonb
  );
